baseurl = "/"
languageCode = "es-es"
languageLang = "es"
title = "Prelima"

[taxonomies]
  proyecto = "proyectos"
  producto = "productos"

[menu]


  [[menu.header]]
    weight = 2
    name = "Sobre Nosotros"
    url = "/#about-us"
  [[menu.header]]
    weight = 3
    name = "Servicios"
    url = "/#services"
  [[menu.header]]
    weight = 4
    name = "Noticias"
    url = "blog/"
  [[menu.header]]
    weight = 5
    name = "Proyectos"
    url = "proyectos/"
  [[menu.header]]
    weight = 6
    name = "Productos"
    url = "productos/"
  [[menu.header]]
    weight = 7
    name = "Contacto"
    url = "/#contact"


  [[menu.footer]]
    weight = 2
    name = "Sobre Nosotros"
    url = "/#about-us"
  [[menu.footer]]
    weight = 3
    name = "Servicios"
    url = "/#services"
  [[menu.footer]]
    weight = 4
    name = "Noticias"
    url = "blog/"
  [[menu.footer]]
    weight = 5
    name = "Proyectos"
    url = "proyectos/"
  [[menu.footer]]
    weight = 6
    name = "Productos"
    url = "productos/"
  [[menu.footer]]
    weight = 7
    name = "Contacto"
    url = "/#contact"
