baseurl = "/"
languageCode = "es-es"
languageLang = "es"
title = "Prelima"

[[menu.footer]]
name = "Contacto"
url = "/#contact"
weight = 6
[[menu.footer]]
name = "Productos"
url = "/productos/"
weight = 5
[[menu.footer]]
name = "Proyectos"
url = "/proyectos/"
weight = 4
[[menu.footer]]
name = "Noticias"
url = "/blog/"
weight = 3
[[menu.footer]]
name = "Servicios"
url = "/#services"
weight = 2
[[menu.footer]]
name = "Sobre Nosotros"
url = "/#about-us"
weight = 1
[[menu.header]]
name = "Proyectos"
url = "proyectos/"
weight = 4
[[menu.header]]
name = "Noticias"
url = "blog/"
weight = 3
[[menu.header]]
name = "Servicios"
url = "/#services"
weight = 2
[[menu.header]]
name = "Sobre Nosotros"
url = "/#about-us"
weight = 1
[[menu.header]]
name = "Contacto"
url = "/#contact"
weight = 6
[[menu.header]]
name = "Productos"
url = "productos/"
weight = 5

[params]
description = '''
Write an awesome description for your new site here. You can edit this
line in config.yml. It will appear in your document head meta (for
Google search results) and in your RSS feed description.
'''

cloudinary_base_url = "https://res.cloudinary.com/prelima/image/upload/"


[taxonomies]
producto = "productos"
proyecto = "proyectos"
