baseurl = "/"
languageCode = "es-es"
languageLang = "es"
title = "Prelima"
[[menu.footer]]
name = "Contacto"
url = "/#contact"
weight = 6
[[menu.footer]]
name = "Productos"
url = "/productos/"
weight = 5
[[menu.footer]]
name = "Proyectos"
url = "/proyectos/"
weight = 4
[[menu.footer]]
name = "Noticias"
url = "/blog/"
weight = 3
[[menu.footer]]
name = "Servicios"
url = "/#services"
weight = 2
[[menu.footer]]
name = "Sobre Nosotros"
url = "/#about-us"
weight = 1
[[menu.header]]
name = "Proyectos"
url = "proyectos/"
weight = 4
[[menu.header]]
name = "Noticias"
url = "blog/"
weight = 3
[[menu.header]]
name = "Servicios"
url = "/#services"
weight = 2
[[menu.header]]
name = "Sobre Nosotros"
url = "/#about-us"
weight = 1
[[menu.header]]
name = "Contacto"
url = "/#contact"
weight = 6
[[menu.header]]
name = "Productos"
url = "productos/"
weight = 5
[taxonomies]
producto = "productos"
proyecto = "proyectos"
